<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8" />
    <title>IT ПРЕДПРИЯТИЕ</title>
    <style>
        /* Общие стили для страницы */
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            font-family: "Times New Roman", serif;
        }

        /* Фон с картинкой */
        .background {
            background: url('1.png') no-repeat center center fixed;
            background-size: cover;
            height: 100vh;
            position: relative;
            color: black;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
        }

        /* Заголовок посередине */
        .background h1 {
            font-size: 5rem;
            margin: 0;
            user-select: none;
        }

        /* Кнопка внизу */
        .background .button-container {
            position: absolute;
            bottom: 50px;
            width: 100%;
            display: flex;
            justify-content: center;
        }

        .background button {
            padding: 15px 40px;
            font-size: 1.5rem;
            font-family: "Times New Roman", serif;
            cursor: pointer;
            background-color: white;
            border: 2px solid black;
            color: black;
            transition: background-color 0.3s, color 0.3s;
        }

        .background button:hover {
            background-color: black;
            color: white;
        }

        /* Скрытый раздел со светлоголубым фоном */
        .new-section {
            display: none;
            height: 100vh;
            background-color: #add8e6; /* светлоголубой */
            color: black;
            font-family: "Times New Roman", serif;
            font-size: 4rem;
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
            padding: 20px;
            box-sizing: border-box;
        }

        .new-section.active {
            display: flex;
        }
    </style>
</head>
<body>
    <div class="background" id="mainSection">
        <h1>IT ПРЕДПРИЯТИЕ</h1>
        <div class="button-container">
            <button id="openBtn">СЮДА</button>
        </div>
    </div>

    <div class="new-section" id="secondSection">
        КРУТЫЕ ПРОГРАММЫ ТОЛЬКО У НАС
    </div>

    <script>
        const openBtn = document.getElementById('openBtn');
        const mainSection = document.getElementById('mainSection');
        const secondSection = document.getElementById('secondSection');

        openBtn.addEventListener('click', () => {
            mainSection.style.display = 'none';      // Скрываем фон с картинкой
            secondSection.classList.add('active');   // Показываем новый раздел
        });
    </script>
</body>
</html>
